title:              Tech Transplanted
email:              rebecca.burwei@gmail.com
description:        A blog for tech workers
author:             Rebecca BurWei
baseurl:            "/"
url:                "https://rebecca-burwei.github.io"

# Google Analytics
google_analytics:   UA-149276100-2
linker_domain_1: rebecca-burwei.github.io
linker_domain_2: techtransplanted.com
linker_domain_3: www.techtransplanted.com

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap 
