title:              Debugging Connections
email:              your-email@example.com
description:        Blog Description
author:             Blog Author
baseurl:            "/debugging-connections"
url:                "https://rebecca-burwei.github.io"

google_analytics:   UA-XXXXXXXXX-X

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap 
